# scripts de bash pasados a playbook
---
- name: Playbook para instalar el back de LAMP
  hosts: backend
  become: yes

  vars_files:
    - ../vars/variables.yml

  tasks:

    - name: Actualizar los repositorios
      apt: 
        update_cache: yes
      # apt update

    - name: Actualizar paquetes instalados
      apt: 
        upgrade: dist
      # apt upgrade -y

    - name: Instalación del gestor de paquetes de Python pip3
      apt:
        name: python3-pip
        state: present
    
    - name: Instalación del módulo de pymysql
      pip:
        name: pymysql
        state: present

    - name: Instalación del sistema gestor de la base de datos
      apt:
        name: mysql-server
        state: present
      # apt install mysql-server -y

    - name: Configuración de MySQL para poder conectar con el frontend
      replace:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: 127.0.0.0
        replace: 0.0.0.0
      # sed -i "s/127.0.0.1/0.0.0.0/" /etc/mysql/mysql.conf.d/mysqld.cnf
    
    - name: Reiniciar el servicio Apache
      service:
        name: apache2
        state: restarted
      # systemctl restart apache2
    
    - name: Crear la base de datos
      mysql_db:
        name: "{{ wp_variables.name }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
      # mysql -u root <<< "DROP DATABASE IF EXISTS $DB_NAME;"
      # mysql -u root <<< "CREATE DATABASE IF NOT EXISTS $DB_NAME;"

    - name: Crear un usuario
      no_log: true
      mysql_user:
        name: "{{ wp_variables.user }}"
        password: "{{ wp_variables.pass }}"
        priv: "{{ wp_variables.name }}.*:ALL"
        host: "%" # sólo cuando hay una máquina para front y otra para back
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
      # mysql -u root <<< "DROP USER IF EXISTS $DB_USER@'%';"
      # mysql -u root <<< "CREATE USER $DB_USER@'%' IDENTIFIED BY '$DB_PASS';"
      # mysql -u root <<< "GRANT ALL PRIVILEGES ON $DB_NAME.* TO $DB_USER@'%';"
      # mysql -u root <<< "FLUSH PRIVILEGES;"

