# scripts de bash pasados a playbook
---
- name: Playbook para instalar WordPress como página principal
  hosts: frontend
  become: yes

  vars_files:
    - ../vars/variables.yml
  
  tasks:

    - name: Obtención del código fuente de WordPress
      get_url:
        url: https://wordpress.org/wordpress-6.1.zip
        dest: /tmp/wordpress.zip
      # wget https://wordpress.org/wordpress-6.1.zip --output-document /tmp/wordpress.zip
    
    - name: Actualizar los repositorios
      apt:
        update_cache: yes
      # apt update 

    - name: Instalar la herramienta unzip
      apt:
        name: unzip
        state: present
      # apt install unzip -y
    
    - name: Eliminar instalaciones previas
      file:
        path: /tmp/wordpress
        state: absent
      # rm -rf /tmp/wordpress 

    - name: Crear la carpeta wordpress
      file:
        path: /tmp/wordpress
        state: directory
        remote_src: yes

    - name: Descomprimir el archivo de WordPress
      unarchive:
        src: /tmp/wordpress.zip
        dest: /tmp/wordpress
        remote_src: yes
      # unzip /tmp/wordpress.zip -d /tmp

    - name: Mover el código fuente al directorio de apache
      copy:
        src: /tmp/wordpress/
        dest: /var/www/html
        remote_src: yes
      # mv /tmp/wordpress/* /var/www/html

    - name: Eliminar el archivo wordpress.zip
      file:
        path: /tmp/wordpress.zip
        state: absent
      # rm -rf /tmp/wordpress.zip

    - name: Localizar y renombrar archivos de configuración
      copy:
        src: /var/www/html/wp-config-sample.php
        dest: /var/www/html/wp-config.php
        remote_src: yes
      # cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php

    - name: Editar el nombre de la base de datos en el archivo de configuración
      replace:
        path: /var/www/html/wp-config.php
        regexp: "database_name_here"
        replace: "{{ wp_variables.name }}"

      # sed -i "s/database_name_here/$DB_NAME/" /var/www/html/wp-config.php
    
    - name: Editar el usuario de la base de datos en el archivo de configuración
      replace: 
        path: /var/www/html/wp-config.php
        regexp: "username_here"
        replace: "{{ wp_variables.user }}"
      # sed -i "s/username_here/$DB_USER/" /var/www/html/wp-config.php
    
    - name: Editar el password del usuario de la base de datos en el archivo de configuración
      replace:
        path: /var/www/html/wp-config.php
        regexp: "password_here"
        replace: "{{ wp_variables.pass }}"
      # sed -i "s/password_here/$DB_PASS/" /var/www/html/wp-config.php
    
    - name: Cambiar la ubicación de la base de datos
      replace:
        path: /var/www/html/wp-config.php
        regexp: "localhost"
        replace: "{{ wp_variables.back }}"
    
    - name: Eliminar el archivo index.html
      file:
        path: /var/www/html/index.html
        state: absent
      # rm -f /var/html/index.html

    - name: Cambiar el propietario y el grupo del directorio
      file:
        path: /var/www/html/
        state: directory
        owner: www-data
        group: www-data
        recurse: yes
      # chown -R www-data:www-data /var/www/html pero sólo de /wordpress