# scripts de bash pasados a playbook
---
- name: Playbook para HTTPS
  hosts: aws
  become: yes

  vars_files:
    - ../vars/variables.yml

  tasks: 

    - name: Instalación del core de snapd
      shell: snap install core
      # snap install core

    - name: Actualización de snapd
      shell: snap refresh core
      # snap refresh core

    - name: Borrado de instalaciones previas de CertBot
      shell: apt-get remove certbot -y
      # apt-get remove certbot -y

    - name: Instalación de CertBot con snapd
      shell: snap install --classic certbot
      # snap install --classic certbot

    # no hace falta
    # - name: Creación de enlace entre el directorio donde se descarga CertBot y usr/bin/certbot
      # ln -s /snap/bin/certbot /usr/bin/certbot

    - name: Solicitud del certificado y configuración del servidor
      shell: certbot --apache -m "{{ https_variables.email }}" --agree-tos --no-eff-email -d "{{ https_variables.domain }}" --non-interactive
      # certbot --apache -m "email" --agree-tos --no-eff-email -d "dominio" --no (o non)-interactive
      # este con shell