# scripts de bash pasados a playbook
---
- name: Playbook para HTTPS
  hosts: aws
  become: yes

  vars_files:
    - ../vars/variables.yml

  tasks: 

    - name: Desinstalaciones previas de certbot
      apt:
        name: certbot
        state: absent

    - name: Instalación del Certbot con snap
      command: snap install --classic certbot
      # snap install core
      
    - name: Crear un alias para el comando certbot
      command: ln -s -f /snap/bin/certbot /usr/bin/certbot

    - name: Solicitud del certificado y configuración del servidor
      command:
        certbot --apache \
        -m "{{ https_variables.email }}" \
        --agree-tos \
        --no-eff-email \
        --non-interactive \
        -d "{{ https_variables.domain  }}"
